"""SurgeForecast model — predicted passenger demand for a route."""

import uuid
from datetime import date

from sqlalchemy import Date, Float, ForeignKey, Integer
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class SurgeForecast(Base):
    """A daily demand forecast for a specific bus route.

    Generated by the Prophet + LSTM hybrid model. Each row represents
    one day's prediction for one route. Used by the operator dashboard
    to anticipate and prepare for surge events.
    """

    __tablename__ = "surge_forecasts"

    route_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("bus_routes.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    forecast_date: Mapped[date] = mapped_column(
        Date, nullable=False, index=True, comment="The date being forecasted"
    )
    surge_probability: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="Probability (0-1) of a surge event on this date",
    )
    predicted_volume: Mapped[int] = mapped_column(
        Integer, nullable=False, comment="Predicted passenger count"
    )

    # Relationships
    route: Mapped["BusRoute"] = relationship("BusRoute", back_populates="forecasts")

    def __repr__(self) -> str:
        return (
            f"<SurgeForecast(route={self.route_id!s}, "
            f"date={self.forecast_date}, "
            f"surge={self.surge_probability:.2f}, "
            f"vol={self.predicted_volume})>"
        )
